export const USERS_GATHER_REQUEST = 'USERS_GATHER_REQUEST';
export const USERS_GATHER_RESOLVE = 'USERS_GATHER_RESOLVE';
export const USERS_GATHER_FAILURE = 'USERS_GATHER_FAILURE';

export const USERS_ADD_REQUEST = 'USERS_ADD_REQUEST';
export const USERS_ADD_RESOLVE = 'USERS_ADD_RESOLVE';
export const USERS_ADD_FAILURE = 'USERS_ADD_FAILURE';

export const USERS_REMOVE_REQUEST = 'USERS_REMOVE_REQUEST';
export const USERS_REMOVE_RESOLVE = 'USERS_REMOVE_RESOLVE';
export const USERS_REMOVE_FAILURE = 'USERS_REMOVE_FAILURE';

export const USERS_LOAD_REQUEST = 'USERS_LOAD_REQUEST';
export const USERS_LOAD_RESOLVE = 'USERS_LOAD_REQUEST';
export const USERS_LOAD_FAILURE = 'USERS_LOAD_REQUEST';
